In [1]:
import numpy as np
import time

In [2]:
# note for numpy
# Python Lists vs NumPy Arrays
# 1. NumPy arrays are faster (optimized in C)
# 2. NumPy stores data in continuous memory blocks
# 3. Uses less memory (optimized storage)
# 4. Built-in mathemetical functions
# 5.Supports direct vectorized operations

In [3]:
# So why is Numpy faster?
# Homogeneous Data Types and Contiguous Memory
# • Vector Operations & C Implementations
# • Reduced Overhead

In [4]:
#execution performance
size=1_000_000
# time
# python list
py_list=list(range(size))
start=time.time()
sq_py_list=[x**2 for x in py_list]
end=time.time()
print(f" taken time by py_list={end-start} second")

             
np_arr=np.array(py_list)
start=time.time()
sq_arrry=np_arr**2 # vectrazition
end=time.time()
print(f" taken time by  np_arr={end-start} second")

 taken time by py_list=0.18055438995361328 second
 taken time by  np_arr=0.006346702575683594 second


In [5]:
import sys
# compresion of ocupied memry 
print(f" occupied memory by py_list={sys.getsizeof(py_list)*len(py_list)} bytes")
print(f" occupied memory by nparray={np_arr.nbytes} bytes")

 occupied memory by py_list=8000056000000 bytes
 occupied memory by nparray=8000000 bytes


In [6]:
# create form of list
# 1 d array
arr=np.array([1,2,3])
print(arr,type(arr),arr.shape)
arr2=np.array([1,2,3,"prime"])
print(arr2,type(arr2),arr2.shape)
# 2d array
arr2d=np.array([[1,2,3,4],[5,6,7,8],[9,8,7,4]])
print(arr2d,type(arr2d),arr2d.shape)

[1 2 3] <class 'numpy.ndarray'> (3,)
['1' '2' '3' 'prime'] <class 'numpy.ndarray'> (4,)
[[1 2 3 4]
 [5 6 7 8]
 [9 8 7 4]] <class 'numpy.ndarray'> (3, 4)


In [7]:
# array create by bulit in function of numpy
arr1=np.zeros((4,3),dtype="int64")# prefill ho jayega
print(arr1,arr1.shape)

arr2=np.ones((4,3),dtype="int64")# prefill ho jayega
print(arr2,arr2.shape)

# for any num prefill in array
arr3=np.full((3,2),12)# prefill ho jayega
print(arr3,arr3.shape)

arr4=np.eye(3,dtype="int64")# identity matrix
print(arr4,arr4.shape)

arr5=np.arange(0,10,2,dtype="int64")# arange array
print(arr5,arr5.shape)

arr6=np.linspace(0,100,4,dtype="int64")# arange array function=np.linspace(startvalue,endingvalue,total value bitween them)
print(arr6,arr6.shape)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]] (4, 3)
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]] (4, 3)
[[12 12]
 [12 12]
 [12 12]] (3, 2)
[[1 0 0]
 [0 1 0]
 [0 0 1]] (3, 3)
[0 2 4 6 8] (5,)
[  0  33  66 100] (4,)


In [8]:
# Array properties
arr=np.array([[1,2,3],[1,2,3],[1,2,3]])
print(arr.shape,arr.size)
print(arr.ndim,arr.dtype)
# if i want to this array convert into floating array then
float_arr=arr.astype(np.float64)
print(float_arr,float_arr.dtype)



(3, 3) 9
2 int64
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]] float64


In [9]:
# Operations on NumPy Arrays
# Reshaping
arr=np.array([[1,2,3,],[4,5,6,]])
print(arr,arr.shape)
reshaped=arr.reshape((3,2))
print(reshaped,reshaped.shape)
# 2d array change into 1d array
flattend=arr.flatten()#2d=>1d
print(flattend,flattend.shape)

# • Indexing (1D & 2D array)
# • Fancy & Boolean Indexing
# · Slicing



[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [52]:
# index of 1d array
arr=np.array([1,2,3])
print(arr[2])
print(arr[0])
# 2d array indexing
arr=np.array([[1,2,3,],[4,5,6,]])
print(arr,arr[0][2])

# fancy indexing
arr=np.array([1,2,3,4,5])
idx=[0,1,3]
print(arr[idx])# it is fancy index specific set of value ke liye 
# bollian indexing mtlb kisi condition ke liye 
arr=np.array([1,2,3,4,5])
print(arr[arr>2])
print(arr[arr>3])
print(arr[arr%2==0])
print(arr[arr%2!=0])
# slicing
arr=np.array([1,2,3,4,5])
print(arr[1:4])
print(arr[:4])
print(arr[1:])
print(arr[1:4:2])# [start:end:step]
# py_list me slice krne pr ek copy create hoti but Numpy me ek view create hota h 
# copy vs view
nums=[1,2,3,4,5]
sub_list=nums[1:3]
print(sub_list)
sub_list[0]=100
print(nums)
print(sub_list)




3
1
[[1 2 3]
 [4 5 6]] 3
[1 2 4]
[3 4 5]
[4 5]
[2 4]
[1 3 5]
[2 3 4]
[1 2 3 4]
[2 3 4 5]
[2 4]
[2, 3]
[1, 2, 3, 4, 5]
[100, 3]


In [29]:
#  Data type
# int type
arr=np.array([1,2,3,4,5])
print(arr,arr.dtype)
# float type
arr=np.array([1,2.0,3,4,5])
print(arr,arr.dtype)
# boolian
arr=np.array([1,2.0,3,4,"Raaz"])
print(arr,arr.dtype)
# complax type
arr1=np.array([1 +3j])
arr2=np.array([4 +2j])
print(arr1+arr2)
print(arr1,arr1.dtype)
# string type it is two types frist is (byte-str),second is (unicode-str)

[1 2 3 4 5] int64
[1. 2. 3. 4. 5.] float64
['1' '2.0' '3' '4' 'Raaz'] <U32
[5.+5.j]
[1.+3.j] complex128


In [30]:
# Multi-dimensional arrays
arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2D)
print(np.sum(arr2D))
sum_of_columns = np.sum(arr2D, axis = 0)
print(sum_of_columns)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]


In [38]:
# 3d array
arr3d=np.array([[[1,2],[3,4],[4,5]],[[5,6],[6,7],[7,8]]])
print(arr3d,arr3d.shape)
# indexing
print(arr3d[1,1,0])
# slicing
print(arr3d[:,0,:])#frist layer both 2d array
print(arr3d[:,:,0])#frist caulm both 2d array
# if i want to chnge the 3d array then
arr3d[:,0,:]=25#frist layer both 2d array
print(arr3d)

[[[1 2]
  [3 4]
  [4 5]]

 [[5 6]
  [6 7]
  [7 8]]] (2, 3, 2)
6
[[1 2]
 [5 6]]
[[1 3 4]
 [5 6 7]]
[[[25 25]
  [ 3  4]
  [ 4  5]]

 [[25 25]
  [ 6  7]
  [ 7  8]]]


In [46]:
# vectorization
arr=np.array([1,2,3,4,5])
print(arr**2)
print(arr+12)

# broadcasting
arr1=np.array([1,2,3,4,5])
arr2=np.array([[1,2,3,4,5],[4,5,6,7,8]])
print(arr1+arr2,arr1.shape,arr2.shape)


[ 1  4  9 16 25]
[13 14 15 16 17]
[[ 2  4  6  8 10]
 [ 5  7  9 11 13]] (5,) (2, 5)


In [54]:
#normalize array means matrix ke each element ka std deviation nikalkr aur arr me se maen ko subtract krke std devition 
# se dive kret h normilized array milta h
arr = np.array([[1, 2], [3, 4]])
mean = np.mean(arr)

std_dev = np.std(arr)
normalized_arr = (arr-mean)/std_dev
print (normalized_arr)
print(mean)
print(std_dev)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895


In [68]:
# important mathematical function
#aggregation

arr=np.array([1,2,3,4,5])
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.var(arr))# varence ko nikalte h 
print(np.std(arr))
print(np.median(arr))
print(np.argmin(arr))# minium vale ka index return krta h 
print(np.argmax(arr))# maxium value ka index return krta h 

# power fnx
arr=np.array([1,2,3,4,5])
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr, 3))

# log fnx
arr=np.array([1,2,3,4,5])
print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

# rounding fnx

print(np.round(3.24))# nearest int  value ke roundup
print(np.floor(3.24))#down value ke liye round up 
print(np.ceil(3.24))# upper value ke liye 
print(np.trunc(3.24)) # trucate krna mtlb decible ke bad ki value cut kr dena

#  extra fnx
arr=np.array([1,-2,3,-4,-5,-5,7,8])
print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr))



15
120
1
5
3.0
2.0
1.4142135623730951
3.0
0
4
[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
3.0
3.0
4.0
3.0
[-5 -4 -2  1  3  7  8]
[-5 -5 -4 -2  1  3  7  8]
[1 2 3 4 5 5 7 8]
